"""存储抽象层的接口定义（Start.md §4 / §6）。"""

from __future__ import annotations

from typing import Any, Callable, Optional, Protocol, runtime_checkable


@runtime_checkable
class Repository(Protocol):
    """关系存储接口（SQLite/MySQL，统一走 SQLAlchemy）。

    具体方法在 models 接入后由 SQLAlchemy session 实现；此处定义最小契约。
    """

    def add(self, entity: Any) -> Any: ...
    def get(self, model: type, pk: Any) -> Optional[Any]: ...
    def list(self, model: type, **filters: Any) -> list[Any]: ...
    def commit(self) -> None: ...


@runtime_checkable
class StateStore(Protocol):
    """热状态/缓存接口（Redis）。键约定见 Start.md §6。"""

    def get(self, key: str) -> Optional[str]: ...
    def set(self, key: str, value: str, ttl: Optional[int] = None) -> None: ...
    def delete(self, key: str) -> None: ...
    def hset(self, key: str, field: str, value: str) -> None: ...
    def hgetall(self, key: str) -> dict[str, str]: ...
    def expire(self, key: str, ttl: int) -> None: ...


@runtime_checkable
class EventBus(Protocol):
    """广播接口（Redis Pub/Sub）。频道约定 ``channel:session:{id}``（§6）。"""

    def publish(self, channel: str, message: str) -> None: ...
    def subscribe(self, channel: str, handler: Callable[[str], None]) -> None: ...
    def unsubscribe(self, channel: str) -> None: ...


@runtime_checkable
class VectorStore(Protocol):
    """向量检索接口（长期记忆召回，Start.md §8）。"""

    def upsert(self, vid: str, vector: list[float], metadata: dict[str, Any]) -> None: ...
    def query(self, vector: list[float], top_k: int = 5) -> list[tuple[str, float, dict]]: ...
    def delete(self, vid: str) -> None: ...
